# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_book_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechValleyTimes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Book')),
            ],
            options={
                'managed': True,
                'db_table': 'tech_valley_times',
            },
        ),
    ]
